"""biginteger

Revision ID: 03983756ade4
Revises: f2aac7806571
Create Date: 2025-09-29 11:20:09.482616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03983756ade4'
down_revision: Union[str, Sequence[str], None] = 'f2aac7806571'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Client_table', sa.Column('client_description', sa.Text(), nullable=True))
    op.add_column('Client_table', sa.Column('client_slogan', sa.Text(), nullable=True))
    op.add_column('Client_table', sa.Column('client_links', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Client_table', 'client_links')
    op.drop_column('Client_table', 'client_slogan')
    op.drop_column('Client_table', 'client_description')
    # ### end Alembic commands ###
