"""connect the table 

Revision ID: 3d4be7c76171
Revises: e8bebbf7f742
Create Date: 2025-10-14 10:03:56.385255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d4be7c76171'
down_revision: Union[str, Sequence[str], None] = 'e8bebbf7f742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_table',
    sa.Column('client_id', sa.String(length=30), nullable=False),
    sa.Column('client_logo', sa.Text(), nullable=True),
    sa.Column('client_company_name', sa.String(length=60), nullable=True),
    sa.Column('client_description', sa.Text(), nullable=True),
    sa.Column('client_slogan', sa.Text(), nullable=True),
    sa.Column('client_links', sa.JSON(), nullable=True),
    sa.Column('client_name', sa.String(length=30), nullable=False),
    sa.Column('clent_email', sa.String(length=30), nullable=False),
    sa.Column('client_phone_no', sa.BigInteger(), nullable=True),
    sa.Column('client_country', sa.String(length=20), nullable=True),
    sa.Column('client_State', sa.String(length=20), nullable=True),
    sa.Column('client_district', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('client_logo')
    )
    op.create_index(op.f('ix_client_table_clent_email'), 'client_table', ['clent_email'], unique=False)
    op.create_index(op.f('ix_client_table_client_id'), 'client_table', ['client_id'], unique=False)
    op.drop_index(op.f('ix_Client_table_clent_email'), table_name='Client_table')
    op.drop_index(op.f('ix_Client_table_client_id'), table_name='Client_table')
    op.drop_table('Client_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Client_table',
    sa.Column('client_id', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('client_logo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('client_company_name', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.Column('client_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('client_slogan', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('client_links', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('client_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('clent_email', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('client_phone_no', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('client_country', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('client_State', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('client_district', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_by', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('client_id', name=op.f('Client_table_pkey')),
    sa.UniqueConstraint('client_logo', name=op.f('Client_table_client_logo_key'))
    )
    op.create_index(op.f('ix_Client_table_client_id'), 'Client_table', ['client_id'], unique=False)
    op.create_index(op.f('ix_Client_table_clent_email'), 'Client_table', ['clent_email'], unique=False)
    op.drop_index(op.f('ix_client_table_client_id'), table_name='client_table')
    op.drop_index(op.f('ix_client_table_clent_email'), table_name='client_table')
    op.drop_table('client_table')
    # ### end Alembic commands ###
