"""connect the table 

Revision ID: 407a21b9533a
Revises: f9da885883c8
Create Date: 2025-10-21 17:58:27.629536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '407a21b9533a'
down_revision: Union[str, Sequence[str], None] = 'f9da885883c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('Client_table_client_logo_key'), 'Client_table', type_='unique')
    op.create_index(op.f('ix_Client_table_clent_email'), 'Client_table', ['clent_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Client_table_clent_email'), table_name='Client_table')
    op.create_unique_constraint(op.f('Client_table_client_logo_key'), 'Client_table', ['client_logo'])
    # ### end Alembic commands ###
