"""create the client_info table

Revision ID: 4e8eb33d4ba3
Revises: 03983756ade4
Create Date: 2025-10-02 08:53:49.383460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e8eb33d4ba3'
down_revision: Union[str, Sequence[str], None] = '03983756ade4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Client_table', 'client_company_name',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=60),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Client_table', 'client_company_name',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###
