"""biginteger

Revision ID: 515b6932f6cf
Revises: 5c02bd27cff1
Create Date: 2025-10-10 19:42:07.695845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '515b6932f6cf'
down_revision: Union[str, Sequence[str], None] = '5c02bd27cff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('App_table',
    sa.Column('App_id', sa.String(length=30), nullable=False),
    sa.Column('Area_id', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_by', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('App_id')
    )
    op.create_index(op.f('ix_App_table_App_id'), 'App_table', ['App_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_App_table_App_id'), table_name='App_table')
    op.drop_table('App_table')
    # ### end Alembic commands ###
