"""biginteger

Revision ID: 5c02bd27cff1
Revises: 6e42ef35dc67
Create Date: 2025-10-10 19:40:25.844409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c02bd27cff1'
down_revision: Union[str, Sequence[str], None] = '6e42ef35dc67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_table', 'App_id',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.drop_column('user_table', 'Area_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('Area_id', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.alter_column('user_table', 'App_id',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###
