"""make company name nullable true

Revision ID: 653998537797
Revises: f9035baeee3f
Create Date: 2025-09-25 14:55:14.258710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '653998537797'
down_revision: Union[str, Sequence[str], None] = 'f9035baeee3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Client_table', 'client_company_name',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('Client_table', 'clent_email',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Client_table', 'clent_email',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('Client_table', 'client_company_name',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###
