"""biginteger

Revision ID: 6e42ef35dc67
Revises: 65011473e390
Create Date: 2025-10-10 14:59:24.421841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e42ef35dc67'
down_revision: Union[str, Sequence[str], None] = '65011473e390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Area_table',
    sa.Column('Area_id', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('button_Name', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('button_id', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('button_type', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('created_by', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Area_id')
    )
    op.create_index(op.f('ix_Area_table_Area_id'), 'Area_table', ['Area_id'], unique=False)
    op.create_table('user_table',
    sa.Column('client_id', sa.String(length=30), nullable=True),
    sa.Column('user_id', sa.String(length=30), nullable=False),
    sa.Column('App_id', sa.String(length=30), nullable=True),
    sa.Column('Area_id', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('Role', sa.String(length=20), nullable=False),
    sa.Column('User_Name', sa.String(length=30), nullable=False),
    sa.Column('user_Email', sa.String(length=30), nullable=False),
    sa.Column('user_PhoneNo', sa.BigInteger(), nullable=False),
    sa.Column('Address', sa.Text(), nullable=False),
    sa.Column('user_country', sa.String(length=20), nullable=True),
    sa.Column('user_State', sa.String(length=20), nullable=True),
    sa.Column('user_district', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_table_client_id'), 'user_table', ['client_id'], unique=False)
    op.create_index(op.f('ix_user_table_user_PhoneNo'), 'user_table', ['user_PhoneNo'], unique=False)
    op.create_index(op.f('ix_user_table_user_id'), 'user_table', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_table_user_id'), table_name='user_table')
    op.drop_index(op.f('ix_user_table_user_PhoneNo'), table_name='user_table')
    op.drop_index(op.f('ix_user_table_client_id'), table_name='user_table')
    op.drop_table('user_table')
    op.drop_index(op.f('ix_Area_table_Area_id'), table_name='Area_table')
    op.drop_table('Area_table')
    # ### end Alembic commands ###
