"""connect the table 

Revision ID: 8d0d9eb1f6ac
Revises: cca603903f32
Create Date: 2025-10-14 19:30:55.113634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d0d9eb1f6ac'
down_revision: Union[str, Sequence[str], None] = 'cca603903f32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('Client_table_client_logo_key'), 'Client_table', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('Client_table_client_logo_key'), 'Client_table', ['client_logo'])
    # ### end Alembic commands ###
