"""create user_table

Revision ID: a49a5d5c7c4f
Revises: 109817557981
Create Date: 2025-10-23 14:00:27.833550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a49a5d5c7c4f'
down_revision: Union[str, Sequence[str], None] = '109817557981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_table_App_id_key'), 'user_table', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_table_App_id_key'), 'user_table', ['App_id'])
    # ### end Alembic commands ###
