"""biginteger

Revision ID: aaff9bef7db9
Revises: 5ba4e2ec3163
Create Date: 2025-10-14 01:19:42.654382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaff9bef7db9'
down_revision: Union[str, Sequence[str], None] = '5ba4e2ec3163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Client_table_clent_email'), 'Client_table', ['clent_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Client_table_clent_email'), table_name='Client_table')
    # ### end Alembic commands ###
