"""create user_table

Revision ID: e4ff0528ace2
Revises: 407a21b9533a
Create Date: 2025-10-21 18:02:36.439083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4ff0528ace2'
down_revision: Union[str, Sequence[str], None] = '407a21b9533a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_table',
    sa.Column('client_id', sa.String(length=30), nullable=True),
    sa.Column('user_id', sa.String(length=30), nullable=False),
    sa.Column('App_id', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('Role', sa.String(length=20), nullable=False),
    sa.Column('User_Name', sa.String(length=30), nullable=False),
    sa.Column('user_Email', sa.String(length=30), nullable=False),
    sa.Column('user_PhoneNo', sa.BigInteger(), nullable=False),
    sa.Column('Address', sa.Text(), nullable=False),
    sa.Column('user_country', sa.String(length=20), nullable=True),
    sa.Column('user_State', sa.String(length=20), nullable=True),
    sa.Column('user_district', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['Client_table.client_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_table_client_id'), 'user_table', ['client_id'], unique=False)
    op.create_index(op.f('ix_user_table_user_Email'), 'user_table', ['user_Email'], unique=True)
    op.create_index(op.f('ix_user_table_user_id'), 'user_table', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_table_user_id'), table_name='user_table')
    op.drop_index(op.f('ix_user_table_user_Email'), table_name='user_table')
    op.drop_index(op.f('ix_user_table_client_id'), table_name='user_table')
    op.drop_table('user_table')
    # ### end Alembic commands ###
