"""biginteger

Revision ID: f7609e217bea
Revises: 515b6932f6cf
Create Date: 2025-10-11 09:17:45.359251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7609e217bea'
down_revision: Union[str, Sequence[str], None] = '515b6932f6cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_table_user_PhoneNo'), table_name='user_table')
    op.create_index(op.f('ix_user_table_user_Email'), 'user_table', ['user_Email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_table_user_Email'), table_name='user_table')
    op.create_index(op.f('ix_user_table_user_PhoneNo'), 'user_table', ['user_PhoneNo'], unique=False)
    # ### end Alembic commands ###
