"""create the client_info table

Revision ID: f9035baeee3f
Revises: 
Create Date: 2025-09-25 11:41:14.981721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9035baeee3f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Client_table',
    sa.Column('client_id', sa.String(length=30), nullable=False),
    sa.Column('client_logo', sa.Text(), nullable=True),
    sa.Column('client_company_name', sa.String(length=10), nullable=False),
    sa.Column('client_name', sa.String(length=30), nullable=False),
    sa.Column('clent_email', sa.String(length=30), nullable=True),
    sa.Column('client_phone_no', sa.Integer(), nullable=True),
    sa.Column('client_country', sa.String(length=20), nullable=True),
    sa.Column('client_State', sa.String(length=20), nullable=True),
    sa.Column('client_district', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('client_logo')
    )
    op.create_index(op.f('ix_Client_table_client_id'), 'Client_table', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Client_table_client_id'), table_name='Client_table')
    op.drop_table('Client_table')
    # ### end Alembic commands ###
