"""connect the table 

Revision ID: f9da885883c8
Revises: 
Create Date: 2025-10-21 17:41:46.578291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9da885883c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Client_table',
    sa.Column('client_id', sa.String(length=30), nullable=False),
    sa.Column('client_logo', sa.Text(), nullable=True),
    sa.Column('client_company_name', sa.String(length=60), nullable=True),
    sa.Column('client_description', sa.Text(), nullable=True),
    sa.Column('client_slogan', sa.Text(), nullable=True),
    sa.Column('client_links', sa.JSON(), nullable=True),
    sa.Column('client_name', sa.String(length=30), nullable=False),
    sa.Column('clent_email', sa.String(length=30), nullable=False),
    sa.Column('client_phone_no', sa.BigInteger(), nullable=True),
    sa.Column('client_country', sa.String(length=20), nullable=True),
    sa.Column('client_State', sa.String(length=20), nullable=True),
    sa.Column('client_district', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('client_logo')
    )
    op.create_index(op.f('ix_Client_table_client_id'), 'Client_table', ['client_id'], unique=False)
    op.create_table('Area_table',
    sa.Column('Area_id', sa.String(length=30), nullable=False),
    sa.Column('button_Name', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('button_id', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('button_type', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('created_by', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Area_id')
    )
    op.create_index(op.f('ix_Area_table_Area_id'), 'Area_table', ['Area_id'], unique=False)
    op.create_table('App_table',
    sa.Column('App_id', sa.String(length=30), nullable=False),
    sa.Column('Area_id', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_by', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('App_id')
    )
    op.create_index(op.f('ix_App_table_App_id'), 'App_table', ['App_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_App_table_App_id'), table_name='App_table')
    op.drop_table('App_table')
    op.drop_index(op.f('ix_Area_table_Area_id'), table_name='Area_table')
    op.drop_table('Area_table')
    op.drop_index(op.f('ix_Client_table_client_id'), table_name='Client_table')
    op.drop_table('Client_table')
    # ### end Alembic commands ###
